### ISSUE TITLE
Button 'Offerte aanvragen' bij pagina Dedicated servers werkt niet.

### ISSUE THREAD

**Issue by jasperberkhout** [ixlhostingbv/website#1]
Zie afbeelding:

![schermafbeelding 2015-08-20 om 16 54 57](https://cloud.githubusercontent.com/assets/11870571/9386545/37353a06-475c-11e5-989d-5655fef5a5c4.png)

**Comment by anno-bit** [comment]
fixed - formulier recht sklapt open

**Comment by jasperberkhout** [comment]
Thanks
