### ISSUE TITLE
Klantgegevens wijzigen

### ISSUE THREAD

**Issue by ixlhosting** [ixlhostingbv/Website#10]
Opmerking klant: "Ik probeer mijn klantgegevens op Mijn iXL aan te passen, maar helaas kom ik niet verder dan het scherm "Een moment geduld a.u.b.". Dit scherm blijft echter een kwartier staan zonder resultaat. "

**Comment by jasperberkhout** [comment]
Zal worden onderzocht! Zodra ik meer weet zal ik dat terugkoppelen.

**Comment by anno-bit** [comment]
Weet je al meer jasper over deze bug?
